export const bruchetta ="../images/bruchetta.jpg";
export const greekSalad="../images/greekSalad.jpg";
export const lemonDessert="../images/lemonDessert.jpg";
export const pizza ="../images/pizza.jpg";
export const strawberryShake="../images/strawberryMilkshake.jpg";
export const moussaka ="../images/moussaka.jpg";
export const paella ="../images/paella.jpg";
export const shakshuka="../images/shakshuka.jpg";
export const spanakopita ="../images/spanakopita.jpg";
export const falafel ="../images/falafel.jpg";
export const ratatouille ="../images/ratatouille.jpg";
export const baklava ="../images/baklava.jpg";
export const kataifi ="../images/kataifi.jpg";
export const galaktoboureko ="../images/galaktoboureko.jpg"
export const tiramisu ="../images/tiramisu.jpg"
